import { IDrinkNew, ICocktail } from "../../entities/cocktails/types/cocktailsTypes";
import drinksData from '../../app/assets/drinks/drinks.json';

export const createNewDrink = (newDrink: IDrinkNew): ICocktail => {
    const currentDate = new Date();
    return {
        idDrink: (drinksData.length + 1).toString(),
        strDrink: newDrink.strDrink,
        strDrinkAlternate: null,
        strTags: null,
        strVideo: null,
        strCategory: newDrink.strCategory,
        strIBA: null,
        strAlcoholic: newDrink.strAlcoholic,
        strGlass: newDrink.strGlass,
        strInstructions: newDrink.strInstructions,
        strInstructionsES: null,
        strInstructionsDE: null,
        strInstructionsFR: null,
        strInstructionsIT: null,
        "strInstructionsZH-HANS": null,
        "strInstructionsZH-HANT": null,
        strDrinkThumb: newDrink.strDrinkThumb,
        strIngredient1: newDrink.strIngredient1,
        strIngredient2: newDrink.strIngredient2,
        strIngredient3: newDrink.strIngredient3,
        strIngredient4: newDrink.strIngredient4,
        strIngredient5: null,
        strIngredient6: null,
        strIngredient7: null,
        strIngredient8: null,
        strIngredient9: null,
        strIngredient10: null,
        strIngredient11: null,
        strIngredient12: null,
        strIngredient13: null,
        strIngredient14: null,
        strIngredient15: null,
        strMeasure1: newDrink.strMeasure1,
        strMeasure2: newDrink.strMeasure2,
        strMeasure3: newDrink.strMeasure3,
        strMeasure4: newDrink.strMeasure4,
        strMeasure5: null,
        strMeasure6: null,
        strMeasure7: null,
        strMeasure8: null,
        strMeasure9: null,
        strMeasure10: null,
        strMeasure11: null,
        strMeasure12: null,
        strMeasure13: null,
        strMeasure14: null,
        strMeasure15: null,
        strImageSource: null,
        strImageAttribution: null,
        strCreativeCommonsConfirmed: null,
        dateModified: currentDate
    };
}